In [1]:
# Import necessary modules

import sys
import os

# Set root folder to project root
os.chdir(os.path.dirname(os.getcwd()))

# Add root folder to path
sys.path.append(os.getcwd())

from src.utils.loading import load_model, get_mazes
from src.utils.plotting import plot_mazes
from src.utils.tda import get_tda
from src.utils.plotting import plot_diagram
from src.utils.tda import Analysis

In [2]:
# Load model and mazes

model = load_model('dt_net')

inputs, solutions = get_mazes(
    dataset='maze-dataset', 
    maze_size=31, 
    num_mazes=5,
    percolation=0.0,
    deadend_start=True)

Using device: mps
Loaded dt_net to mps


AssertionError: 

In [ ]:
#start_latents = 1000

#latents = model.input_to_latent(inputs)
#latents = model.latent_forward(latents,inputs,iters=list(range(start_latents,1401)))

RuntimeError: Invalid buffer size: 39.79 GB

In [ ]:
print(latents.shape)

torch.Size([401, 5, 128, 24, 24])


In [ ]:
#diagram, betti_nums, p_scores = get_tda(latents[:,:10,:,:,:].cpu().numpy())

    Performing TDA with embed_dim = 25, delay = 1, and X.shape = (401, 5, 128, 24, 24) (0.591GB)
    Flattened X.shape = (401, 368640)
    Normalize rows of X.shape = (401, 368640)
    Reduced X.shape = (401, 401) (0.001GB)
    Computed distance_matrix.shape = (376, 376)


In [ ]:
analysis = Analysis([51], 10, 'dt_net', list(range(1000,1401)), 25, 1, 0.5)

Using device: mps
Loaded dt_net to mps


In [ ]:
analysis.analyze()

Analyzing dt_net on 5 mazes of size 9 ...
    Loaded mazes in 0.01s
    Computed latent series in 0.73s
    Performing TDA with embed_dim = 25, delay = 1, and X.shape = (401, 128, 24, 24) (0.118GB)
    Flattened X.shape = (401, 73728)
    Normalize rows of X.shape = (401, 73728)
    Reduced X.shape = (401, 401) (0.001GB)
    Computed distance_matrix.shape = (376, 376)
    Analyzed maze 1 of 5 in 9.93s
    Computed latent series in 0.72s
    Performing TDA with embed_dim = 25, delay = 1, and X.shape = (401, 128, 24, 24) (0.118GB)
    Flattened X.shape = (401, 73728)
    Normalize rows of X.shape = (401, 73728)
    Reduced X.shape = (401, 401) (0.001GB)
    Computed distance_matrix.shape = (376, 376)
    Analyzed maze 2 of 5 in 11.71s
    Computed latent series in 0.72s
    Performing TDA with embed_dim = 25, delay = 1, and X.shape = (401, 128, 24, 24) (0.118GB)
    Flattened X.shape = (401, 73728)
    Normalize rows of X.shape = (401, 73728)
    Reduced X.shape = (401, 401) (0.001GB)
  

In [ ]:
print(analysis.betti_nums)

[[[  1   0   0]
  [375   0   0]
  [  1   0   0]
  [  1   0   0]
  [  1   0   0]]]
